export const TEST_NODES_PORT_VARIABLE = 3000;
export const TEST_INVOKING_ENDPOINTS_PORT_VARIABLE = 4000;

process.env.NODES_PORT = TEST_NODES_PORT_VARIABLE.toString();
process.env.INVOKING_ENDPOINTS_PORT =
  TEST_INVOKING_ENDPOINTS_PORT_VARIABLE.toString();
