name: CD

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    uses: Interconnected-project/broker_service/.github/workflows/reusable-test.yml@master

  deploy-docker-image:
    needs: test
    uses: Interconnected-project/broker_service/.github/workflows/reusable-deploy-docker.yml@master
    with:
      image_name: ${{ github.event.repository.name }}
      tag: ${{github.ref_name}}
    secrets:
      registry_username: ${{secrets.DOCKERHUB_USERNAME}}
      registry_password: ${{secrets.DOCKERHUB_PASSWORD}}
