name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:

  test:
    uses: Interconnected-project/broker_service/.github/workflows/reusable-test.yml@master

  cpd:
    uses: Interconnected-project/broker_service/.github/workflows/reusable-cpd.yml@master

  update-badges:
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: [test, cpd]
    uses: Interconnected-project/broker_service/.github/workflows/reusable-badges.yml@master
