name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Login to DockerHub Registry
        run: echo ${{secrets.registry_password}} | docker login -u ${{secrets.registry_username}} --password-stdin
      
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.registry_username}}/${{inputs.image_name}}:${{inputs.tag}} --tag ${{secrets.registry_username}}/${{inputs.image_name}}:latest

      - name: Push the latest Docker image
        run: docker push ${{secrets.registry_username}}/${{inputs.image_name}} --all-tags